services:
  stacks_db:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: stacks_db
      POSTGRES_HOST_AUTH_METHOD: trust
  redis_db:
    image: redis:7-alpine
    container_name: redis
    ports:
      - 6379:6379
